


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "octave_nexus"
version = "2.0.0"
description = "Offline wallet program for Aptos."
authors = []
readme = "vehicles/octave_nexus/readme.md"
packages = [
    { include = "octave_nexus", from = "vehicles" },
]
license = "Mix: GPL-3.0-only for originals + Laboratory Rules"

exclude = [
	"vehicles/octave_nexus/_status/DB/**"
]
include = [
	"vehicles/octave_nexus/sveltnetics_packets/**/*",
]


[tool.poetry.scripts]
octave_nexus = 'octave_nexus:clique'

[tool.poetry.dependencies]
python = "^3.10"
#
Emergency = "^2.0.0"
somatic = "^3.0.3"
ships = "^1.3.8"
ventures = "^3.0.0" 
#
click = "^8.1.7"
pydash = "^8.0.1"
requests = "^2.32.3"
rich = "^13.9.2"
sanic = "^23.12.0"
#
cx_Freeze = "^7.2.3"
#
pipdeptree = "^2.23.4"
pip-licenses = "^5.0.0"


#
#
#	This one is because... "ships" is broken.. or something.
#
#
pyasyncore = "^1.0.4"

# ecdsa = "0.18.0"
# h2 = "^4.1.0"
# httpx = "^0.24.0"
# PyNaCl = "^1.5.0"
# tomli = "^2.0.1"
# typing-extensions = "^4.4.0"


