[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nowledge-mem"
version = "1.0.2"
description = "A Python MCP server for Nowledge Mem"
readme = "README.md"
authors = [
    {name = "Nowledge Labs, LLC", email = "hello@nowledge-labs.ai"},
    {name = "Wey Gu", email = "weyl.gu@gmail.com"}
]
license = {text = "Apache-2.0"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
  "fastmcp>=2.12.4"
]

[tool.setuptools]
packages = ["server"]

[project.scripts]
bundle-deps = "python:install_deps"

# Custom scripts section for DXT development
[tool.dxt]
bundle = "pip install \"mcp[all]\" --target server/lib --upgrade --force-reinstall"
test = "python server/main.py --debug"
pack = "npx @anthropic-ai/dxt pack"