[tool.poetry]
name = "dreamstone"
version = "0.1.5"
description = "Secure hybrid RSA + AES encryption library with CLI"
authors = ["Renks"]
readme = "README.md"
license = "MIT"
packages = [{ include = "dreamstone", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
cryptography = "^45.0.5"
typer = {extras = ["all"], version = "^0.16.0"}

[tool.poetry.scripts]
dreamstone = "dreamstone.cli.main:app"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "-v"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
