[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ctu_crs"
version = "1.0.6"
description = "Package to control CTU/CIIRC robots CRS93 and CRS97 via MARS control unit."
authors = [
    {name = "Vladimir Petrik", email = "vladimir.petrik@cvut.cz"},
]
dependencies = [
    "ctu-mars-control-unit>=0.1.3",
    "numpy>=2.1.2",
    "pypylon>=4.2.0",
    "pyyaml>=6.0.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "BSD 3-Clause"}

[project.scripts]
move_crs93 = "ctu_crs.scripts.move_crs93:main"
move_crs97 = "ctu_crs.scripts.move_crs97:main"

[project.optional-dependencies]
dev = [
    "black>=25.9.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "ruff>=0.13.2",
]

[tool.setuptools.package-data]
"ctu_crs" = ["*.yaml"]
