[project]
name = "wagtail-notes"
version = "1.0.3"
authors = [
  { name="Bertrand Bordage", email="bordage.bertrand@gmail.com" },
]
description = "Adds anchor links and related backlinks to the Wagtail editor (Draftail). Useful for footnotes and more!"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["wagtail-font-awesome-svg"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {text = "BSD-3-Clause"}

[project.urls]
Homepage = "https://github.com/noripyt/wagtail-notes"
Issues = "https://github.com/noripyt/wagtail-notes/issues"
