[project]
name = "ltts"
version = "0.2.3" # Updated by github action
description = "Text-to-speech CLI using Kokoro TTS"
readme = "README.md"
license = "MIT"
authors = [{name = "Frank Chiarulli Jr."}]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "kokoro>=0.9.4",
    "misaki[ja,zh]>=0.9.4",
    "pip>=25.2",
    "soundfile>=0.13.1",
    "sounddevice>=0.4.6",
    "torch>=2.8.0",
    "unidic>=1.1.0",
]

[project.urls]
Repository = "https://github.com/fcjr/ltts"
Issues = "https://github.com/fcjr/ltts/issues"

[project.scripts]
ltts = "ltts:main"

[tool.uv]
package = true
