[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sqlalchemy_helper_tool"
version = "1.7.2"
description = "Package to work with mysql database from python"
readme = "README.md"
authors = [
    { name = "Anabel Reyes", email = "anakings95@gmail.com" }
]
maintainers = [
    { name = "Anabel Reyes", email = "anakings95@gmail.com" }  
]
license = {file = "LICENSE.txt"} 
keywords = [
    "Database"
]

dependencies = [
    "SQLAlchemy==1.4.39",
    "pandas==2.1.1",
    "numpy==1.26.1",
    "PyMySQL==1.0.3",
    "pyodbc>=4.0.39"
]

requires-python = ">=3.7"

[project.urls]
Homepage = "https://github.com/anakings/sqlalchemy_helper_tool"
Documentation = "https://github.com/anakings/sqlalchemy_helper_tool/blob/feature/sqlalchemy_helper_tool/README.md"


[tool.setuptools]
packages = ["sqlalchemy_helper_tool"]