[project]
name = "woolworm"
version = "0.0.10"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "loguru>=0.7.3",
  "marker-pdf[full]>=1.9.3",
  "ollama>=0.5.4",
  "opencv-python>=4.12.0.88",
  "psutil>=7.1.0",
  "pytesseract>=0.3.13",
  "scikit-image>=0.25.2",
  "scipy>=1.16.2",
  "typer<0.17.0",
]
[tool.setuptools]
packages = ["woolworm"]
