[tool.poetry]
name = "pipeline-eds"
version = "0.2.106"
description = "The API pipeline library, with CLI tools. Key target: The Emerson Ovation EDS REST API."
authors = ["George Clayton Bennett <george.bennett@memphistn.gov>"]
license = "BSD-3"
readme = "README.md"
packages = [
    { include = "pipeline", from = "src" },
	{ include = "workspaces", from = "." }
] # This makes `pipeline` available as an importable top-level module
homepage = "https://github.com/city-of-memphis-wastewater/pipeline"
repository = "https://github.com/city-of-memphis-wastewater/pipeline"
include = [
    "src/pipeline/data/*"
]
	
[tool.poetry.scripts]
pipeline = "pipeline.cli:app" # for installation of pipeline as a CLI. Ex: pipeline trend M100FI -s June3 -f June17
eds = "pipeline.cli:app" # alias eds for pipeline CLI
pipeline-eds = "pipeline.cli:app" # alias eds for pipeline CLI


[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
#addopts = "--cov=pipeline --cov-report=html" #  visually inspect coverage, e.g. before a release or PR.
addopts = "-ra --cov=pipeline --cov-report=term-missing" # for development â€” fast and informative in terminal.
testpaths = ["tests"]
pythonpath = ["src", "."]

[tool.poetry.dependencies]
python = ">=3.8.0,<4.0.0"
requests = ">=2.32.3,<3.0.0"
toml = ">=0.10.2,<0.11.0"
pyyaml = ">=6.0.2,<7.0.0"
schedule = ">=1.2.2,<2.0.0"
#fastapi = ">=0.115.12,<0.116.0"
pydantic = "1.10.13"
urllib3 = "^2.4.0"
plotly = "^6.2.0"
uvicorn = "^0.34.3"
mysql-connector-python = "^9.3.0"
tzdata = "^2025.2"
pendulum = "^3.1.0"
fastapi = "^0.116.1"
rich = "^14.1.0"
typer = "^0.17.4"
keyring = "^25.6.0"
keyrings-alt = "^5.0.2"
# These dependencies are only installed when the 'windb' extra is specified
pyodbc = { version = "^5.1.0", optional = true }
matplotlib = { version = "^3.10.6", optional = true }
cherrypy = "^18.10.0"

[tool.poetry.extras] # pipx install pipeline-eds[windows]
windows = ["pyodbc","matplotlib"]
mpl = ["matplotlib"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-cov = "^6.2.1"
pygal = "^3.0.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."scripts"]
controller = "pipeline.daemon.controller:main_cli"
