[project]
name = "PlasmidFinder"
dynamic = []
description = "The service identifies plasmids in total or partial sequenced isolates of bacteria."
authors = [
    { name = "Center for Genomic Epidemiology", email = "food-cgehelp@dtu.dk" },
]
dependencies = [
    "cgecore>=1.5.5",
    "tabulate>=0.7.7",
    "pandas",
    "biopython",
]
requires-python = ">=3.10"
readme = "README.md"
version = "3.0.0"

[project.license]
text = "Apache 2.0"

[project.optional-dependencies]

[tool.pdm]
package-dir = "src"
packages = [
    "plasmidfinder",
]

[tool.pdm.version]
source = "file"
path = "src/plasmidfinder/__init__.py"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.1.2",
]

[tool.pdm.scripts]
test = "python -m pytest tests/"
plasmidfinder = "python -m plasmidfinder"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
