[project]
name = "crypticorn"
description = "Maximise Your Crypto Trading Profits with Machine Learning"
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
authors = [{name = "Crypticorn", email = "timon@crypticorn.com"}]
version = "3.1.0-rc.2"
keywords = ["machine learning", "data science", "crypto", "modelling"]
dynamic = ["dependencies", "optional-dependencies"]

classifiers = [
    "Topic :: Scientific/Engineering",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Typing :: Typed",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["crypticorn*"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements/main.txt"] }
optional-dependencies.dev = { file = ["requirements/dev.txt"] }
optional-dependencies.extra = { file = ["requirements/extra.txt"] }

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version:nf",] # https://python-semantic-release.readthedocs.io/en/latest/configuration.html#version-toml
commit_message = "Python Release v{version}\n\nAutomatically generated by python-semantic-release" # https://python-semantic-release.readthedocs.io/en/latest/configuration.html#commit-message
build_command = "pip install build && python -m build" # https://python-semantic-release.readthedocs.io/en/latest/configuration.html#build-command

# https://python-semantic-release.readthedocs.io/en/latest/configuration.html#exclude-commit-patterns
#[tool.semantic_release.changelog.exclude_commit_patterns]
# Potentially exclude commit patterns from the changelog

# [tool.semantic_release.changelog]
# mode = "update"
# insertion_flag = "<!-- changelog-insertion -->"

# [tool.semantic_release.changelog.default_templates]
# changelog_file = "CHANGELOG.md"

# https://python-semantic-release.readthedocs.io/en/latest/multibranch_releases.html#multibranch-releases
[tool.semantic_release.branches.v3-dev]
match = "v3-dev"
prerelease = true
prerelease_token = "rc"

[tool.semantic_release.branches.v3]
match = "v3"
prerelease = false


[project.urls]
Homepage = "https://crypticorn.com"
Documentation = "https://docs.crypticorn.com"
Dashboard = "https://app.crypticorn.com"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
