[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[project]
authors = []
requires-python = ">=3.10.0,<4.0.0"
dependencies = [
    "ollama>=0.6.0,<1.0.0",
    "langchain-core>=1.0.0a6,<2.0.0",
]
name = "langchain-ollama"
version = "1.0.0a1"
description = "An integration package connecting Ollama and LangChain"
readme = "README.md"

[project.license]
text = "MIT"

[project.urls]
"Source Code" = "https://github.com/langchain-ai/langchain/tree/master/libs/partners/ollama"
"Release Notes" = "https://github.com/langchain-ai/langchain/releases?q=tag%3A%22langchain-ollama%3D%3D0%22&expanded=true"
repository = "https://github.com/langchain-ai/langchain"

[dependency-groups]
test = [
    "pytest>=8.4.1,<9.0.0",
    "pytest-asyncio>=0.26.0,<1.0.0",
    "pytest-socket>=0.7.0,<1.0.0",
    "pytest-watcher>=0.4.3,<1.0.0",
    "syrupy>=4.9.1,<5.0.0",
    "langchain-core",
    "langchain-tests",
]
test_integration = []
lint = [
    "ruff>=0.13.1,<0.14.0",
]
dev = [
    "langchain-core",
]
typing = [
    "mypy>=1.17.1,<2.0.0",
    "langchain-core",
]

[tool.uv.sources.langchain-core]
path = "../../core"
editable = true

[tool.uv.sources.langchain-tests]
path = "../../standard-tests"
editable = true

[tool.mypy]
disallow_untyped_defs = "True"

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 100

[tool.ruff.lint]
select = [
    "ALL",
]
ignore = [
    "COM812",
    "ISC001",
    "PERF203",
    "S112",
    "RUF012",
    "SLF001",
    "UP007",
    "UP045",
    "FIX002",
    "TD002",
    "TD003",
    "TC002",
    "TC003",
    "PLR0912",
    "PLR0915",
    "C901",
    "FBT001",
    "ERA001",
    "ANN401",
]
unfixable = [
    "B028",
]

[tool.ruff.lint.pydocstyle]
convention = "google"
ignore-var-parameters = true

[tool.ruff.lint.per-file-ignores]
"tests/**" = [
    "D",
]

[tool.ruff.lint.extend-per-file-ignores]
"tests/**/*.py" = [
    "S101",
    "S311",
    "ARG001",
    "PLR2004",
    "PT011",
]
"scripts/*.py" = [
    "INP001",
]

[tool.coverage.run]
omit = [
    "tests/*",
]

[tool.pytest.ini_options]
addopts = "--snapshot-warn-unused --strict-markers --strict-config --durations=5"
markers = [
    "compile: mark placeholder test used to compile integration tests without running them",
]
asyncio_mode = "auto"
