dependencies:
  - gitlab_path: cta-computing/dpps/bdms/bdms
    revision: v0.4.1

  - gitlab_path: cta-computing/dpps/workload/wms
    revision: v0.3.2

  - gitlab_path: cta-computing/dpps/simpipe/simpipe
    revision: v0.2.0
    sonar_project_key: gammasim_simtools_AY_ssha9WiFxsX-2oy_w

  - gitlab_path: cta-computing/dpps/datapipe/datapipe
    revision: v0.2.1

  - gitlab_path: cta-computing/dpps/calibrationpipeline/calibpipe
    revision: v0.2.0

  - gitlab_path: cta-computing/dpps/qualpipe/qualpipe
    revision: v0.2.1

  - gitlab_path: cta-computing/dpps/aiv/cvmfs
    revision: v0.4.0
