[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ApkPatcher-install"
version = "1.0"
authors = [
  { name = "RK_TECHNO_INDIA", email = "TechnoIndian786@gmail.com" }
]

description = "Smali Patcher ( Bypass ð’ SSL & Flutter SSL, VPN, USB Debugging, Screen Restrict, One Device Login, Spoof Info & Package Detection, Ads, AES Logs Inject )"

license = { file = "LICENSE" }
readme = "README.md"

requires-python = ">=3.12"
dependencies = ["requests", "r2pipe", "asn1crypto", "multiprocess"]

keywords = ["ApkPatcher"]

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Assemblers",
]

[project.scripts]
ApkPatcher = "ApkPatcher.APK_PATCHER:RK_Techno_IND"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"ApkPatcher" = ["AES.smali", "lib_Pairip_CoreX.so"]

[project.urls]
Homepage = "https://github.com/TechnoIndian/ApkPatcher"
Repository = "https://github.com/TechnoIndian/ApkPatcher.git"
Issues = "https://github.com/TechnoIndian/ApkPatcher/issues"

[tool.black]
line-length = 79
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 79