[tool.poetry]
name = "PyHaste"
version = "1.1.4"
description = "Python code speed analyzer"
authors = ["Janne Enberg <janne.enberg@lietu.net>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://github.com/cocreators-ee/pyhaste/"
repository = "https://github.com/cocreators-ee/pyhaste/"
documentation = "https://github.com/cocreators-ee/pyhaste/"
keywords = ["performance", "measuring", "benchmark", "benchmarking", "analyzer"]
packages = [
    { include = "pyhaste/*.py" },
]


[tool.poetry.dependencies]
python = "^3.11"
rich = "^13.7.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-watcher = "^0.4.2"
pytest-asyncio = "^0.23.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
asyncio_mode = "auto"

[tool.ruff]
line-length = 110
